### ISSUE TITLE
Remember data to repeat fingerprint

### ISSUE THREAD

**Issue by youra-h** [pavlealeksic/puppeteer-afp#2]
Hi!
Can you be able to remember data in the future? To get the same fingerprint later.

**Comment by emmmhx** [comment]
Hi. Did you manage to find any solution to this?

**Comment by youra-h** [comment]
> Hi. Did you manage to find any solution to this?

Hey!  I postponed this project for no need, but I can say that it is not difficult to implement it on your own.  I just wanted this solution to be included, so I opened the problem on github

**Comment by pavlealeksic** [comment]
Options are added to support this
