### ISSUE TITLE
fingerprint based on Browser and os.

### ISSUE THREAD

**Issue by Mkopl360** [pavlealeksic/puppeteer-afp#5]
sometime we do need specific user agent and OS for  work.
its possible to define multiple browser and OS to generate fingerprint for each page ?

**Comment by pavlealeksic** [comment]
For this case you would need to create multiple browser instances and run afp for each one

**Comment by Mkopl360** [comment]
ok but how to instruct afp generator to generate fingerprint for specific browser and OS based fingerprint ?

**Comment by pavlealeksic** [comment]
Fingerprint isnt dependent on os and browser, just with using these options in the newest version you can generate

**Comment by LeninZapata** [comment]
> ok but how to instruct afp generator to generate fingerprint for specific browser and OS based fingerprint ?

What you are asking for is complicated, I have not found a Node plugin that allows joining the OS with the Platform where the bots are executed. I have tested it with more than 10 antibot pages but the platform somehow catches it. I think you have to Disassembly the chromium.exe to achieve this feat.
